name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.1"
      - name: npm install
        run: npm install
      - name: yarn build
        run: yarn run build
